### ISSUE TITLE
Implement /api/v1/auth/hospital/register Endpoint in Flask

### ISSUE THREAD

**Issue by AnarchyNinetyNine** [AnarchyNinetyNine/bloodlink#1]
### **_Issue Summary_**
Develop the /api/v1/auth/hospital/register endpoint to allow hospitals to register on the platform. The backend logic will handle form submissions, validate input data, hash passwords, and store hospital information in the database using Flask and SQLAlchemy.

Form Demo: Below is a reference image of the hospital registration form that this endpoint will handle 
![Screenshot from 2024-12-10 14-17-28](https://github.com/user-attachments/assets/09e3236d-0e99-46b9-b6b3-6da21b5bd66d)

### **_Requirements_**
1. **Request Method:** POST
2. **Endpoint:** /api/v1/auth/hospital/register
3. **Request Body** (JSON format):
{
  "name": "General Hospital",
  "email": "admin@generalhospital.com",
  "password": "securepassword123",
  "phoneNumber": "1234567890",
  "role": "HOSPITAL"
}

### **_Validation Rules:_**

- All fields are required.
- **email** and **phoneNumber** must be unique.
- **Password** should be hashed before storage.
- The **role** must match one of the **UserRole** enum values.

### **_Database Model:_** 

Use the **Hospital model** with fields such as **_name_**, **_email_**, **_password_**, **_role_**, and **phoneNUmber**

### **_Success Response:_**

{
  "message": "Registration successful"
}

**HTTP Status:** 201 Created

### **_Error Responses:_**

- Missing required fields: 400 Bad Request
- Duplicate **email** or **phoneNumber**: 409 Conflict
- Internal server error: 500 Internal Server Error

### **_Technologies:_**

- Flask for API development.
- SQLAlchemy for ORM.
- Bcrypt for password hashing.

### **_Implementation Steps_**

- **Form Design:** Reference or design the hospital registration form UI.
- **Define the Route:** Use Flask to define the POST route for /api/v1/auth/hospital/register.
- **Validate Input:** 
1. Check for required fields.
2. Ensure email and phone number are unique in the database.
- **Password Handling:** Hash the password using bcrypt.
- **Database Interaction:** Save the hospital's details into the hospitals table.
- **Response Handling:** Return appropriate success or error responses.

**Comment by Wikki2000** [comment]
Implemented the registration endpoint for hospital
